### PR TITLE
Retry put_record_batch when the server gives response with error.

### PR DESCRIPTION
**Pull request by jiohyoo**
This PR changed put_record_batch() to retry when the server gives response with error, as currently it does not handle any failed requests.

### CODE REVIEW

**Comment by jiohyoo** [comment]
@winebarrel Hi, here's my PR for adding retry feature for kinesis firehose and would be great if I can use this feature for myself! Thanks

**Comment by jessecollier** [comment]
@winebarrel is it possible to get this released ? you have any comments?

**Comment by winebarrel** [comment]
Thank you for pull request! I'm sorry reply late.
I will release a new version on the weekend.

**Comment by winebarrel** [comment]
[v0.1.2.beta](https://rubygems.org/gems/fluent-plugin-kinesis-firehose/versions/0.1.2.beta) has been released.
Please try it out.

**Pull request merged**
